type = "javascript"
workers_dev = true
name = "mugtungshing-development"
[vars]
  ENVIRONMENT = "development"
  

[env.staging]
  name = "mugtungshing-staging"
  workers_dev = true
  [env.staging.vars]
    ENVIRONMENT = "staging"

[env.production]
  name = "mugtungshing"
  [env.production.vars]
    ENVIRONMENT = "production"

[build]
  command = "yarn build"
    [build.upload]
    format = "service-worker"