type = "webpack"
zone_id = ""
account_id = ""
workers_dev = true
webpack_config = "webpack.config.js"
name = "mugtungshing-development"
[vars]
  ENVIRONMENT = "development"

[env.staging]
  name = "mugtungshing-staging"
  workers_dev = true
  [env.staging.vars]
    ENVIRONMENT = "staging"

[env.production]
  name = "mugtungshing"
  [env.production.vars]
    ENVIRONMENT = "production"
